export const APP_META = {
  name: 'Ghép & Chuẩn Hóa Dữ Liệu KSK HIS',
  shortName: 'HIS Excel Matcher',
  appCode: 'HISMATCH',
  version: '1.0.4',
  releaseDate: '2026-10-04',
  description: 'Ghép dữ liệu khám sức khỏe từ VNPT-HIS & Danh sách Bìa sang File Mẫu Chuẩn NSN, hỗ trợ nạp nhiều file / nạp dồn / thay thế trực tiếp tại giao diện nạp và kết quả, cảnh báo trùng tên tuổi và xuất Excel chuẩn General Text.',
  author: {
    name: 'Nguyễn Sơn Nam',
    alias: 'Nsnnam / NamNS / NSN',
    role: 'Tác giả & Nhà phát triển phần mềm Y tế',
    email: 'akahimachi@gmail.com',
    zalo: '0977059075',
    github: 'https://github.com/Nsnnam',
    repo: 'https://github.com/Nsnnam/nsn-his-excel-matcher',
    webUrl: 'https://nsnnam.github.io/nsn-his-excel-matcher/',
  },
  coffee: {
    bank: 'BIDV',
    branch: 'PGD Nguyễn Tất Thành',
    accountNumber: '8855989777',
    accountName: 'NGUYEN SON NAM',
    qrPath: 'coffee-qr.jpg',
  },
  timezone: 'Asia/Ho_Chi_Minh',
  changelog: [
    {
      version: '1.0.4',
      date: '2026-10-04',
      features: [
        'Hỗ trợ nạp dồn nhiều file cùng lúc cho cả File 1 (HIS .xls/.xlsx) và File 2 (Danh sách Bìa .xlsx/.xls) qua nút "+ Thêm file" hoặc kéo thả nhiều file.',
        'Hỗ trợ cơ chế thay thế trực tiếp: Thay thế toàn bộ danh sách file hoặc thay thế từng file đơn lẻ bằng nút "🔄 Thay" ngay trên danh sách nạp.',
        'Tự động đối soát và cho phép chọn sheet độc lập cho từng file Bìa khi import nhiều file khác nhau.',
        'Thanh quản lý file tương tác trực tiếp ngay tại màn hình kết quả đối soát (ResultsFileManagerBar): Cho phép thêm mới, thay thế hoặc xóa file mà không cần quay lại màn hình ban đầu.',
        'Cơ chế re-matching tự động tức thì: Ngay khi thêm, thay thế hoặc xóa file ở màn hình kết quả, hệ thống tự động đối soát lại toàn bộ dữ liệu ngay lập tức.',
      ],
    },
    {
      version: '1.0.3',
      date: '2026-10-01',
      features: [
        'Nhận diện linh hoạt và mở rộng tối đa các biến thể cột Tên công ty trên sheet Bìa (TENCTY, Tên C.ty, C.ty, Cơ quan, CT, CQ, Đơn vị, Doanh nghiệp...).',
        'Tự động lấy trực tiếp từ cột "Nơi làm việc" trong file HIS nếu không tìm thấy cột tên công ty ở file sheet Bìa hoặc ô dữ liệu bị trống.',
        'Cơ chế fallback thông minh: Tự động kế thừa "Nơi làm việc" chung của đợt khám từ file HIS cho toàn bộ danh sách, đảm bảo 100% dòng dữ liệu xuất ra file FileMauChuan_NsN.xlsx đều có Tên C.ty chuẩn xác.',
        'Đồng bộ cập nhật trường Tên C.ty khi người dùng hiệu chỉnh thủ công hoặc chọn ứng viên từ HIS.',
      ],
    },
    {
      version: '1.0.2',
      date: '2026-09-29',
      features: [
        'Tự động ẩn khung nạp 2 file đầu vào sau khi ghép dữ liệu xong, tập trung màn hình vào Thống kê, Khối xuất Excel nổi bật và Bảng đối chiếu.',
        'Bổ sung thanh điều khiển nhỏ gọn cho phép nhấp "Hiện khung nạp file" hoặc "Xóa DS" bất cứ lúc nào.',
        'Cố định tên file xuất ra thành FileMauChuan_NsN.xlsx (bỏ timestamp) phục vụ trực tiếp phần mềm in tem BarTender (.btw) và Mail Merge.',
        'Thêm khối biểu ngữ CTA tải file FileMauChuan_NsN.xlsx siêu nổi bật ngay trên đầu bảng kết quả.',
      ],
    },
    {
      version: '1.0.1',
      date: '2026-09-29',
      features: [
        'Tối ưu hóa đối soát Ngày sinh & Tuổi: Cùng họ tên nhưng khác ngày sinh/tuổi là 2 người khác nhau, tự động xếp vào Khớp chuẩn 1-1 và bỏ qua cảnh báo.',
        'Chỉ cảnh báo đối với trường hợp trùng lặp thực sự: Cùng họ tên VÀ cùng ngày tháng năm sinh / cùng tuổi trên HIS.',
        'Bổ sung banner xanh báo trạng thái tích cực "0 Cảnh báo" khi toàn bộ danh sách được ghép chuẩn xác.',
      ],
    },
    {
      version: '1.0.0',
      date: '2026-09-29',
      features: [
        'Khóa truy cập bảo mật qua mã popup chuẩn NSN (namns).',
        'Tự động đọc file xuất HIS (.xls dạng HTML table hoặc .xlsx) và Danh sách hồ sơ (sheet Bìa).',
        'Ghép chính xác dựa trên Tên và Giới tính, hỗ trợ đối soát Ngày sinh/CCCD/SĐT khi cùng tên.',
        'Hệ thống cảnh báo nổi bật các trường hợp trùng tên, cùng tên tuổi để người dùng kiểm tra và hiệu chỉnh.',
        'Cho phép hiệu chỉnh hoặc chọn thủ công hồ sơ ghép trực tiếp trên giao diện bảng.',
        'Chuẩn hóa triệt để dữ liệu: loại bỏ khoảng trắng thừa đầu/cuối, chuẩn hóa Unicode NFC.',
        'Xuất file Excel đúng 100% định dạng File Mẫu Chuẩn NSN (11 cột: STT, Mã BA, Mã BN, Tên bệnh nhân, Ngày sinh, Tuổi, Giới tính, Bộ phận, SĐT, Tên C.ty, Địa Chỉ).',
        'Tất cả cột xuất ra quy ước kiểu General Text (@) chống nuốt số 0 ở đầu SĐT và CCCD.',
        'Nút Xóa danh sách (Clear Import) chuẩn NSN làm sạch toàn bộ trạng thái dữ liệu.',
        'Hoạt động 100% Offline trên trình duyệt, không gửi dữ liệu y tế ra ngoài.',
      ],
    },
  ],
};
