export const APP_META = {
  name: 'Ghép & Chuẩn Hóa Dữ Liệu KSK HIS',
  shortName: 'HIS Excel Matcher',
  appCode: 'HISMATCH',
  version: '1.0.0',
  releaseDate: '2026-09-29',
  description: 'Ghép dữ liệu khám sức khỏe từ VNPT-HIS & Danh sách Bìa sang File Mẫu Chuẩn NSN, cảnh báo trùng tên tuổi và xuất Excel chuẩn General Text.',
  author: {
    name: 'Nguyễn Sơn Nam',
    alias: 'Nsnnam / NamNS / NSN',
    role: 'Tác giả & Nhà phát triển phần mềm Y tế',
    email: 'akahimachi@gmail.com',
    zalo: '0977059075',
    github: 'https://github.com/Nsnnam',
    repo: 'https://github.com/Nsnnam/nsn-his-excel-matcher',
    webUrl: 'https://nsnnam.github.io/nsn-his-excel-matcher/',
  },
  coffee: {
    bank: 'BIDV',
    branch: 'PGD Nguyễn Tất Thành',
    accountNumber: '8855989777',
    accountName: 'NGUYEN SON NAM',
    qrPath: 'coffee-qr.jpg',
  },
  timezone: 'Asia/Ho_Chi_Minh',
  changelog: [
    {
      version: '1.0.0',
      date: '2026-09-29',
      features: [
        'Khóa truy cập bảo mật qua mã popup chuẩn NSN (namns).',
        'Tự động đọc file xuất HIS (.xls dạng HTML table hoặc .xlsx) và Danh sách hồ sơ (sheet Bìa).',
        'Ghép chính xác dựa trên Tên và Giới tính, hỗ trợ đối soát Ngày sinh/CCCD/SĐT khi cùng tên.',
        'Hệ thống cảnh báo nổi bật các trường hợp trùng tên, cùng tên tuổi để người dùng kiểm tra và hiệu chỉnh.',
        'Cho phép hiệu chỉnh hoặc chọn thủ công hồ sơ ghép trực tiếp trên giao diện bảng.',
        'Chuẩn hóa triệt để dữ liệu: loại bỏ khoảng trắng thừa đầu/cuối, chuẩn hóa Unicode NFC.',
        'Xuất file Excel đúng 100% định dạng File Mẫu Chuẩn NSN (11 cột: STT, Mã BA, Mã BN, Tên bệnh nhân, Ngày sinh, Tuổi, Giới tính, Bộ phận, SĐT, Tên C.ty, Địa Chỉ).',
        'Tất cả cột xuất ra quy ước kiểu General Text (@) chống nuốt số 0 ở đầu SĐT và CCCD.',
        'Nút Xóa danh sách (Clear Import) chuẩn NSN làm sạch toàn bộ trạng thái dữ liệu.',
        'Hoạt động 100% Offline trên trình duyệt, không gửi dữ liệu y tế ra ngoài.',
      ],
    },
  ],
};
